spring:
  datasource:
    url: jdbc:mysql://article-database-service:3306/article-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user-app
    password: secret-app

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        use_sql_comments: true
  cache:
    type: redis
  data:
    redis:
      host: article-cache-service
      port: 6379