# FROM 에 대해 알아본다.
#
# 문법
#   FROM <이미지 명>
#   FROM <이미지 명>:<태그 명>
#
# 의미
#   특정 이미지를 베이스 이미지로 사용하여, 추가적인 설정을 이어나가서 새로운 도커 이미지를 만들때 사용한다.


# 예시
#   openjdk(도커허브의 openjdk:17-jdk) 가 설치된 상태의 컨테이너가 만들어지는 이미지를 생성해주는 도커 파일이다.
# 이미지 생성
#   docker build -t openjdk-17-image .
FROM openjdk:17-jdk